version : "3.3"
services:
  database:
    image: mysql:latest
    restart: always
    container_name: mungdb
    environment:
      MYSQL_DATABASE: mungdb
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: savememungz-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mungdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge
